name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm
      - name: Start validator
        uses: metaplex-foundation/actions/start-validator@v1
        with:
          node: ${{ matrix.node_version }}
          solana: ${{ env.SOLANA_VERSION }}
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
